package db;

import java.sql.*;
import java.util.NoSuchElementException;

/**
 * A Publishing company that can own series and movies
 */
public class Company extends ActiveDomainObject {

    private String comp_name;
    private String country;
    private String address;
    private String url;

    public Company(int comp_id, String comp_name, String country, String address, String url) {
        this.ID = comp_id;
        this.comp_name = comp_name;
        this.country = country;
        this.address = address;
        this.url = url;
    }

    public Company(String comp_name, String country, String address, String url) {
        this(-1, comp_name, country, address, url);
    }

    public String getName() {
        return comp_name;
    }

    public void setName(String comp_name) {
        this.comp_name = comp_name;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }
    

    public static Company get(String constraint) throws SQLException {
        Company res;
        Statement stmt = conn.createStatement();
        // Select all from an object satisfying contstraints
        ResultSet rs = stmt.executeQuery("select * from Company where " + constraint);

        if (!rs.next()) {
            throw new NoSuchElementException("Ingen treff.");
        } 
        res = new Company(
            rs.getInt("comp_id"),
            rs.getString("comp_name"),
            rs.getString("country"),
            rs.getString("address"),
            rs.getString("url")
        );

        if (rs.next()) {
            throw new NoSuchElementException("Mer enn ett treff!");
        }

        return res;
    }

    /**
     * Save object to database
     * 
     * Inserts object if ID=-1, otherwise updates the entry with id=ID
     */
    @Override
    public void save() {
        try {
            PreparedStatement stmt;
            if (ID == -1) {
                stmt = conn.prepareStatement("insert into Company (comp_name, country, address, url) values (?, ?, ?, ?)", Statement.RETURN_GENERATED_KEYS);
            } else {
                // Only update if object already exists in db
                stmt = conn.prepareStatement("update Person set comp_name=?, country=?, address=?, url=? where comp_id=" + this.ID);
            }
            stmt.setString(1, this.comp_name);
            stmt.setString(2, this.country);
            stmt.setString(3, this.address);
            stmt.setString(4, this.url);
            stmt.executeUpdate();
            conn.commit();
            
            if (ID == -1) {
                // Update with autogenerated pk
                ResultSet rs = stmt.getGeneratedKeys();
                rs.next();
                this.ID = rs.getInt(1);
            }
        } catch (Exception e) {
            System.out.println("Feil under databaseoperasjon: "+e);
        }
    }
}