package db;

import java.sql.*;
import java.util.*;

public class User extends ActiveDomainObject {
    
    private String username;

    public User (int id, String username) {
        this.ID = id;
        this.username = username;
    }
    
    /**
     * Get a User object matching the given constraints
     * @param constraint an expression e.g. "user_id=1"
     * @return object of type User
     * @throws NoSuchElementException if there were no or mutliple matches
     * @throws SQLException database error
     */
    public static User get(String constraint) throws NoSuchElementException, SQLException {
        User res;
        try {
            Statement stmt = conn.createStatement();
            // Select all from an object satisfying contstraints
            ResultSet rs = stmt.executeQuery("select * from User where " + constraint);

            if (!rs.next()) {
                throw new NoSuchElementException("Ingen treff.");
            } 
            res = new User(
                rs.getInt("user_id"),
                rs.getString("username")
            );

            if (rs.next()) {
                throw new NoSuchElementException("Mer enn ett treff!");
            }

            return res;

        } catch (SQLException e) {
            System.out.println("Feil under databaseoperasjon "+e);
            return null;
        }
    }

    @Override
    public void save () {
        try {
            PreparedStatement stmt;
            if (ID == -1) {
                stmt = conn.prepareStatement("insert into UserProfile (username) values (?)", Statement.RETURN_GENERATED_KEYS);
            } else {
                // Only update if object already exists in db
                stmt = conn.prepareStatement("update UserProfile set username=? where user_id=" + this.ID);
            }
            stmt.setString(1, this.username);
            stmt.executeUpdate();
            conn.commit();
            
            if (ID == -1) {
                // Update with autogenerated pk
                ResultSet rs = stmt.getGeneratedKeys();
                rs.next();
                this.ID = rs.getInt(1);
            }
        } catch (Exception e) {
            System.out.println("db error during update of bruker="+e);
        }
    }
    
}